version: "3.8"
services: 
  tracing_database:
    build: ./database
    ports: 
      - 5432:5432
  
  backend:
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
      - tracing_database
